version: '3.8'
services:
  mysql:
    image: "mysql:8.0"
    ports:
      - 3307:3306
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: discount_test
      MYSQL_USER: discount_test
      MYSQL_PASSWORD: discount_test
